apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: miltonrodrigues/gitops
  newTag: 33cfb5925e0a3b7e00b806129068da3c210d408c
